version: "3.9"
services:
  postgres_app:
    container_name: postgres_app
    image: postgres
    volumes:
      - ./db-data-app:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=db_app_user
      - POSTGRES_PASSWORD=db_app_password
      - POSTGRES_DB=fullstackapp
    ports:
      - "6432:5432"
    networks:
      - backend
  postgres_kc:
    container_name: postgres_kc
    image: postgres
    volumes:
      - ./db-data-kc:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: db_kc_user
      POSTGRES_PASSWORD: db_kc_password
      POSTGRES_DB: keycloak
    ports:
      - "5432:5432"
    networks:
      - backend
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: default@stelmaszak.eu
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    networks:
      - backend
  keycloak:
    container_name: keycloak
    image: bitnami/keycloak
    volumes:
      - ./keycloak/realm:/opt/bitnami/keycloak/data/import
    environment:
      - KEYCLOAK_ADMIN_USER=admin
      - KEYCLOAK_ADMIN_PASSWORD=password
      - DEBUG=true
      - DEBUG_PORT=*:9797
      - KEYCLOAK_DATABASE_HOST=postgres_kc
      - KEYCLOAK_DATABASE_PORT=5432
      - KEYCLOAK_DATABASE_USER=db_kc_user
      - KEYCLOAK_DATABASE_PASSWORD=db_kc_password
      - KEYCLOAK_DATABASE_NAME=keycloak
      - KEYCLOAK_DATABASE_SCHEMA=public
      - KEYCLOAK_EXTRA_ARGS=--import-realm
      - TZ=Europe/Paris
      - KEYCLOAK_JDBC_PARAMS=useSSL=false&allowPublicKeyRetrieval=true&connectTimeout=30000
    depends_on:
      - postgres_kc
    ports:
      - "8180:8080"
      - "9797:9797"
    networks:
      - backend

networks:
  backend:
    name: backend
    driver: bridge
